apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog
  namespace: PLACEHOLDER   
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
    spec:
      containers:
        - name: product-catalog
          image: ghcr.io/${{ github.repository_owner }}/product-catalog:${{ github.sha }}
          ports:
            - containerPort: 80
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: product-catalog-secrets
                  key: api-key
