apiVersion: v1
kind: Service
metadata:
  name: product-catalog-svc
  namespace: PLACEHOLDER
spec:
  selector:
    app: product-catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
