name: CD-TEST

on:
  workflow_dispatch:  # Elle tetiklenebilen test etme

jobs:
  simulate-deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate Faulty Production Deploy
        run: |
          echo "⚠️ Simulating faulty production deployment for product-catalog..."
          exit 1  # ← Bilinçli hata üret

  rollback-on-failure:
    needs: simulate-deploy-production
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Rollback Deployment (Test)
        run: |
          echo "❌ Deploy başarısız oldu, rollback başlatılıyor..."
          echo "Komut: kubectl rollout undo deployment/product-catalog -n production"
