# product-catalog/.github/workflows/cd.yml
name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  deploy-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Simulate Deploy to staging
        run: |
          echo "Simulating: kubectl apply --validate=false -f k8s/deployment.yaml -n staging"
          echo "Simulating: kubectl apply --validate=false -f k8s/service.yaml    -n staging"

  pause-for-approval:
    needs: deploy-staging
    runs-on: ubuntu-latest
    steps:
      - name: **MANUAL APPROVAL REQUIRED**
        run: |
          echo "Waiting for manual approval to proceed to production..."
          # Bu adım tasarımda, gerçek onay burada alınacak

  deploy-production:
    needs: pause-for-approval
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Simulate Deploy to production
        run: |
          echo "Simulating: kubectl apply --validate=false -f k8s/deployment.yaml -n production"
          echo "Simulating: kubectl apply --validate=false -f k8s/service.yaml    -n production"

      - name: Notify Slack (design only)
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"✅ product-catalog production’a deploy edildi."}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}

  rollback-strategy:
    name: Rollback Strategy (docs)
    runs-on: ubuntu-latest
    steps:
      - name: Document Rollback Command
        run: |
          echo "Rollback komutu:"
          echo "kubectl rollout undo deployment/product-catalog -n production"
